apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mxxocus59-go 
  janus-idp.io/tekton: mxxocus59-go
  backstage.io/kubernetes-id: mxxocus59-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mxxocus59-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  